### ISSUE TITLE
合作申请

### ISSUE THREAD

**Issue by CJZHAOSHANG** [U1805/blue-archive-gacha-simulator#1]
hello~
   我这边有一个其他游戏的抽卡开发需求，请问有兴趣合作一下吗？如果方便可以联系一下我。微信：SkEbOm

**Comment by U1805** [comment]
你好~

很抱歉，我恐怕不能胜任这个需求。如你所见，这个仓库只是我一时兴起建立的，功能上还有很多不足，比如没有声音、没有自动更新卡池角色、没有实现卡池切换等，代码的解耦也不太理想。我原计划下个月有空再重构这个项目，还需要很长时间来摸索和完善。非常感谢你的邀请，祝你顺利找到合适的合作伙伴！(๑•̀ㅂ•́)و✧

**Comment by CJZHAOSHANG** [comment]
能加个微信不，留个联系方式

**Comment by CJZHAOSHANG** [comment]
能添加个微信，保留个联系方式
